// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.webfrontend.domain;

import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TimeoUser_Roo_Configurable {
    
    declare @type: TimeoUser: @Configurable;
    
}
