// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.task.domain;

import org.poormanscastle.products.timeo.task.domain.Goal;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Goal_Roo_Configurable {
    
    declare @type: Goal: @Configurable;
    
}
