// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.task.domain;

import java.io.Serializable;
import org.poormanscastle.products.timeo.task.domain.Priority;

privileged aspect Priority_Roo_Serializable {
    
    declare parents: Priority implements Serializable;
    
    private static final long Priority.serialVersionUID = 1L;
    
}
