// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.task.domain;

import java.io.Serializable;
import org.poormanscastle.products.timeo.task.domain.Status;

privileged aspect Status_Roo_Serializable {
    
    declare parents: Status implements Serializable;
    
    private static final long Status.serialVersionUID = 1L;
    
}
