// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.webfrontend.domain;

import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUserDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TimeoUserDataOnDemand_Roo_Configurable {
    
    declare @type: TimeoUserDataOnDemand: @Configurable;
    
}
