// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.webfrontend.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUser;
import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUserDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect TimeoUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimeoUserDataOnDemand: @Component;
    
    private Random TimeoUserDataOnDemand.rnd = new SecureRandom();
    
    private List<TimeoUser> TimeoUserDataOnDemand.data;
    
    public TimeoUser TimeoUserDataOnDemand.getNewTransientTimeoUser(int index) {
        TimeoUser obj = new TimeoUser();
        setLoginId(obj, index);
        setPassword(obj, index);
        setStakeholderId(obj, index);
        return obj;
    }
    
    public void TimeoUserDataOnDemand.setLoginId(TimeoUser obj, int index) {
        String loginId = "loginId_" + index;
        obj.setLoginId(loginId);
    }
    
    public void TimeoUserDataOnDemand.setPassword(TimeoUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void TimeoUserDataOnDemand.setStakeholderId(TimeoUser obj, int index) {
        String stakeholderId = "stakeholderId_" + index;
        obj.setStakeholderId(stakeholderId);
    }
    
    public TimeoUser TimeoUserDataOnDemand.getSpecificTimeoUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TimeoUser obj = data.get(index);
        String id = obj.getId();
        return TimeoUser.findTimeoUser(id);
    }
    
    public TimeoUser TimeoUserDataOnDemand.getRandomTimeoUser() {
        init();
        TimeoUser obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getId();
        return TimeoUser.findTimeoUser(id);
    }
    
    public boolean TimeoUserDataOnDemand.modifyTimeoUser(TimeoUser obj) {
        return false;
    }
    
    public void TimeoUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TimeoUser.findTimeoUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TimeoUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TimeoUser>();
        for (int i = 0; i < 10; i++) {
            TimeoUser obj = getNewTransientTimeoUser(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
