// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.poormanscastle.products.timeo.webfrontend.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUser;
import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUserDataOnDemand;
import org.poormanscastle.products.timeo.webfrontend.domain.TimeoUserIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TimeoUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TimeoUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TimeoUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TimeoUserIntegrationTest: @Transactional;
    
    @Autowired
    TimeoUserDataOnDemand TimeoUserIntegrationTest.dod;
    
    @Test
    public void TimeoUserIntegrationTest.testCountTimeoUsers() {
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", dod.getRandomTimeoUser());
        long count = TimeoUser.countTimeoUsers();
        Assert.assertTrue("Counter for 'TimeoUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TimeoUserIntegrationTest.testFindTimeoUser() {
        TimeoUser obj = dod.getRandomTimeoUser();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to provide an identifier", id);
        obj = TimeoUser.findTimeoUser(id);
        Assert.assertNotNull("Find method for 'TimeoUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TimeoUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TimeoUserIntegrationTest.testFindAllTimeoUsers() {
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", dod.getRandomTimeoUser());
        long count = TimeoUser.countTimeoUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'TimeoUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TimeoUser> result = TimeoUser.findAllTimeoUsers();
        Assert.assertNotNull("Find all method for 'TimeoUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TimeoUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TimeoUserIntegrationTest.testFindTimeoUserEntries() {
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", dod.getRandomTimeoUser());
        long count = TimeoUser.countTimeoUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TimeoUser> result = TimeoUser.findTimeoUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TimeoUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TimeoUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TimeoUserIntegrationTest.testFlush() {
        TimeoUser obj = dod.getRandomTimeoUser();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to provide an identifier", id);
        obj = TimeoUser.findTimeoUser(id);
        Assert.assertNotNull("Find method for 'TimeoUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTimeoUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TimeoUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimeoUserIntegrationTest.testMergeUpdate() {
        TimeoUser obj = dod.getRandomTimeoUser();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to provide an identifier", id);
        obj = TimeoUser.findTimeoUser(id);
        boolean modified =  dod.modifyTimeoUser(obj);
        Integer currentVersion = obj.getVersion();
        TimeoUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TimeoUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimeoUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", dod.getRandomTimeoUser());
        TimeoUser obj = dod.getNewTransientTimeoUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TimeoUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TimeoUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TimeoUserIntegrationTest.testRemove() {
        TimeoUser obj = dod.getRandomTimeoUser();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeoUser' failed to provide an identifier", id);
        obj = TimeoUser.findTimeoUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TimeoUser' with identifier '" + id + "'", TimeoUser.findTimeoUser(id));
    }
    
}
